### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by DmytroKosiczenko** [DimaKosiczenko/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by DmytroKosiczenko** [comment]
**### The most successful person** in life is a person who is happy.

And a happy man is a man who **_does the work he loves doing_** the most. He **_loves his job_**. Unfortunately not all of us are blessed with jobs that we love doing.

A happy man’s job should make his parents happy as well. They should be wholeheartedly proud of their son’s/daughter’s dream job. And sadly not everybody’s parents approve of their kid’s dream job.

A **_successful man is blessed with a happy family_**. A spouse to live by and good kids make a beautiful home. Coming home from work shouldn’t be a pain for him. He would rather be most happy around his kids that love to play with his hair.

A successful man should have faced hurdles and he should’ve been able to **_accept the hard reality and move on hoping for the best but prepared for the worst_**.

A **_successful man should have enough money and literacy_**. Too much or too little of these would only make him successful in one aspect but a miserable failure in the other.

**Comment by DimaKosiczenko** [comment]
₴ранд мерсі!
